name: Add the label to cards

on:
  workflow_dispatch:
  project_card:
    types: [moved]
    
jobs:
  checkForContent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        if: github.event_name == 'project_card' && github.event.project_card        
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const result = await github.projects.getCard({
              context.project_card.id,
            });

            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              labels: 'live',
            });
