name: Add the label to cards

on:
  workflow_dispatch:
  project_card:
    types: [moved]
    
jobs:
  add-label-to-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
      - uses: actions/github-script@v3
        if: github.event_name == 'project_card' && github.event.project_card.content_url        
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = await github.request(context.payload.project_card.content_url)
            console.log(issue)
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              labels: 'live',
            });
