name: Add the label to cards

on:
  workflow_dispatch:
  project_card:
    types: [moved]
    
jobs:
  add-label-to-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        if: github.event_name == 'project_card' && github.event.project_card.content_url && github.event.project_card.column_id == 13354989      
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = await github.request(context.payload.project_card.content_url)
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.data.number,
              labels: ['live'],
            });
      - uses: actions/github-script@v3
        if: github.event_name == 'project_card' && github.event.project_card.content_url && github.event.project_card.column_id == 13354976      
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = await github.request(context.payload.project_card.content_url)
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.data.number,
              labels: ['publish'],
            });
  remove-label-from-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        if: github.event_name == 'project_card' && github.event.project_card.content_url && github.event.project_card.changes.column_id == 13354989      
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = await github.request(context.payload.project_card.content_url)
            github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.data.number,
              name: 'live',
            });
      - uses: actions/github-script@v3
        if: github.event_name == 'project_card' && github.event.project_card.content_url && github.event.project_card.column_id == 13354976      
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = await github.request(context.payload.project_card.content_url)
            github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.data.number,
              name: 'publish',
            });
